version: '3'
services:
  redis-master:
    build: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_ROLE=master
  redis-slave:
    build: redis
    ports:
      - "6380:6379"
    environment:
      - REDIS_ROLE=slave
  sentinel:
    build: redis
    